"""new database structure

Revision ID: 04e93b6e5ac9
Revises: 
Create Date: 2024-07-15 10:53:39.471077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e93b6e5ac9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='内部ID'),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_name', sa.String(length=128), nullable=True, comment='商品名称'),
    sa.Column('primary_sku_id', sa.String(length=128), nullable=True, comment='主SKU ID, 部分系统可用'),
    sa.Column('brand', sa.String(length=64), nullable=True, comment='品牌'),
    sa.Column('product_url', sa.String(length=1024), nullable=True, comment='商品链接'),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True, comment='评分'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='评论数'),
    sa.Column('rating_count', sa.Integer(), nullable=True, comment='评分数'),
    sa.Column('attributes', sa.JSON(), nullable=True, comment='额外商品属性, 特点, 和描述bulletedCopyAttrs'),
    sa.Column('description', sa.String(length=1024), nullable=True, comment='描述'),
    sa.Column('attributes_raw', sa.JSON(), nullable=True, comment='原始属性'),
    sa.Column('category', sa.String(length=256), nullable=True, comment='商品类别'),
    sa.Column('gender', sa.String(length=16), nullable=True, comment='性别'),
    sa.Column('released_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='上新时间'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('is_review_analyzed', sa.Boolean(), nullable=True, comment='是否已分析'),
    sa.Column('review_analyses', sa.JSON(), nullable=True, comment='评论分析结果汇总'),
    sa.Column('extra_review_analyses', sa.JSON(), nullable=True, comment='额外评论分析结果汇总'),
    sa.Column('extra_metrics', sa.JSON(), nullable=True, comment='额外评论指标'),
    sa.Column('review_statistics', sa.JSON(), nullable=True, comment='评论分析统计'),
    sa.Column('extra_review_statistics', sa.JSON(), nullable=True, comment='额外评论分析统计'),
    sa.Column('review_summary', sa.String(length=2048), nullable=True, comment='评论总结'),
    sa.Column('remark', sa.String(length=1024), nullable=True, comment='备注'),
    sa.Column('category_id', sa.BigInteger(), nullable=True, comment='类别ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('gathered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='采集时间'),
    sa.Column('last_gathered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最近采集时间'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品'
    )
    op.create_index(op.f('ix_product_released_at'), 'product', ['released_at'], unique=False)
    op.create_index('ix_source_product_id', 'product', ['source', 'product_id'], unique=False)
    op.create_table('product_review',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=True, comment='源评论ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_id', sa.String(length=64), nullable=True, comment='商品ID'),
    sa.Column('sku_id', sa.String(length=64), nullable=True, comment='SKU ID'),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True, comment='评分'),
    sa.Column('title', sa.String(length=1024), nullable=True, comment='评论标题'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评论内容'),
    sa.Column('photos', sa.JSON(), nullable=True, comment='评论图片'),
    sa.Column('outer_photos', sa.JSON(), nullable=True, comment='评论外部数据源'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('helpful_votes', sa.Integer(), nullable=True, comment='按顶票数'),
    sa.Column('not_helpful_votes', sa.Integer(), nullable=True, comment='按踩票数'),
    sa.Column('helpful_score', sa.Numeric(precision=6, scale=1), nullable=True, comment='有用评分'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('gathered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='内部创建时间'),
    sa.Column('last_gathered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='内部更新时间'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品评论'
    )
    op.create_index('ix_source_product_id', 'product_review', ['source', 'product_id'], unique=False, mysql_using='hash')
    op.create_table('product_review_analysis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=True, comment='源评论ID'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='版本ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_id', sa.String(length=64), nullable=True, comment='商品ID'),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='评论指标'),
    sa.Column('quality', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品质量指标'),
    sa.Column('warmth', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品保暖性指标'),
    sa.Column('comfort', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品舒适度指标'),
    sa.Column('softness', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品柔软性指标'),
    sa.Column('preference', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品偏好指标'),
    sa.Column('repurchase_intent', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品回购意愿指标'),
    sa.Column('appearance', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品外观指标'),
    sa.Column('fit', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品合身度指标'),
    sa.Column('extra_metrics', sa.JSON(), nullable=True, comment='额外评论指标'),
    sa.Column('token_usage', sa.JSON(), nullable=True, comment='LLM token 消耗'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品评论分析, 支持版本号管理'
    )
    op.create_table('product_review_translation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=True, comment='源评论ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_id', sa.String(length=64), nullable=True, comment='商品ID'),
    sa.Column('sku_id', sa.String(length=64), nullable=True, comment='SKU ID, 部分系统支持sku_id区分'),
    sa.Column('language_code', sa.String(length=16), nullable=False, comment='语言代码'),
    sa.Column('title', sa.String(length=1024), nullable=True, comment='评论标题'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评论内容'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品评论翻译'
    )
    op.create_index('ix_source_product_id', 'product_review_translation', ['source', 'product_id'], unique=False)
    op.create_index('ix_source_review_id', 'product_review_translation', ['source', 'review_id'], unique=False)
    op.create_table('product_sku',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='内部ID'),
    sa.Column('sku_id', sa.String(length=128), nullable=True, comment='源SKU ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.Column('size', sa.String(length=64), nullable=True, comment='尺码'),
    sa.Column('color', sa.String(length=64), nullable=True, comment='颜色'),
    sa.Column('material', sa.String(length=128), nullable=True, comment='材质'),
    sa.Column('source_id', sa.BigInteger(), nullable=True, comment='源商品ID'),
    sa.Column('sku_name', sa.String(length=128), nullable=True, comment='SKU名称'),
    sa.Column('product_url', sa.String(length=1024), nullable=True, comment='商品链接'),
    sa.Column('image_url', sa.String(length=512), nullable=True, comment='商品图片'),
    sa.Column('outer_image_url', sa.String(length=1024), nullable=True, comment='商品图片外链'),
    sa.Column('model_image_urls', sa.JSON(), nullable=True, comment='模特图片链接列表'),
    sa.Column('outer_model_image_urls', sa.JSON(), nullable=True, comment='外部模特图片链接列表'),
    sa.Column('inventory', sa.Integer(), nullable=True, comment='库存'),
    sa.Column('inventory_status', sa.String(length=32), nullable=True, comment='库存状态'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('gathered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='抓取时间'),
    sa.Column('last_gathered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最近抓取时间'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品SKU'
    )
    op.create_index('ix_source_product_id', 'product_sku', ['source', 'product_id'], unique=False, mysql_using='hash')
    op.create_index('ix_source_sku_id', 'product_sku', ['source', 'sku_id'], unique=False, mysql_using='hash')
    op.create_table('product_sku_translation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='内部ID'),
    sa.Column('sku_id', sa.String(length=128), nullable=True, comment='源SKU ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.Column('language_code', sa.String(length=16), nullable=False, comment='语言代码'),
    sa.Column('size', sa.String(length=64), nullable=True, comment='尺码'),
    sa.Column('color', sa.String(length=64), nullable=True, comment='颜色'),
    sa.Column('material', sa.String(length=128), nullable=True, comment='材质'),
    sa.Column('sku_name', sa.String(length=128), nullable=True, comment='SKU名称'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品SKU翻译'
    )
    op.create_index('ix_source_sku_id', 'product_sku_translation', ['source', 'sku_id'], unique=False)
    op.create_table('product_translation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='内部ID'),
    sa.Column('language_code', sa.String(length=16), nullable=False, comment='语言'),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_name', sa.String(length=128), nullable=True, comment='商品名称'),
    sa.Column('brand', sa.String(length=64), nullable=True, comment='品牌'),
    sa.Column('attributes', sa.JSON(), nullable=True, comment='额外商品属性, 特点, 和描述bulletedCopyAttrs'),
    sa.Column('description', sa.String(length=1024), nullable=True, comment='描述'),
    sa.Column('attributes_raw', sa.JSON(), nullable=True, comment='原始属性'),
    sa.Column('category', sa.String(length=256), nullable=True, comment='商品类别'),
    sa.Column('gender', sa.String(length=16), nullable=True, comment='性别'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('review_analyses', sa.JSON(), nullable=True, comment='评论分析结果汇总'),
    sa.Column('extra_review_analyses', sa.JSON(), nullable=True, comment='额外评论分析结果汇总'),
    sa.Column('extra_metrics', sa.JSON(), nullable=True, comment='额外评论指标'),
    sa.Column('review_statistics', sa.JSON(), nullable=True, comment='评论分析统计'),
    sa.Column('extra_review_statistics', sa.JSON(), nullable=True, comment='额外评论分析统计'),
    sa.Column('review_summary', sa.String(length=2048), nullable=True, comment='评论总结'),
    sa.Column('remark', sa.String(length=1024), nullable=True, comment='备注'),
    sa.Column('category_id', sa.BigInteger(), nullable=True, comment='类别ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品翻译'
    )
    op.create_index('ix_source_product_id', 'product_translation', ['source', 'product_id'], unique=False)
    op.create_table('product_detail',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='内部ID'),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('store', sa.String(length=64), nullable=True, comment='所属商店'),
    sa.Column('material', sa.String(length=128), nullable=True, comment='材质'),
    sa.Column('neckline', sa.String(length=128), nullable=True, comment='领口'),
    sa.Column('fabric', sa.String(length=128), nullable=True, comment='面料名称'),
    sa.Column('origin', sa.String(length=128), nullable=True, comment='产地'),
    sa.Column('length', sa.String(length=128), nullable=True, comment='服装长度'),
    sa.Column('fit', sa.String(length=128), nullable=True, comment='合身度'),
    sa.Column('vendor', sa.String(length=64), nullable=True, comment='供应商'),
    sa.Column('clothing_details', sa.String(length=1024), nullable=True, comment='服装细节'),
    sa.Column('package_quantity', sa.Integer(), nullable=True, comment='包装数量'),
    sa.Column('care_instructions', sa.String(length=1024), nullable=True, comment='护理和清洁'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='原始数据, json字段'),
    sa.Column('parent_category', sa.String(length=256), nullable=True, comment='父商品类别'),
    sa.Column('category_breadcrumbs', sa.String(length=1024), nullable=True, comment='商品类别级联'),
    sa.Column('sub_category', sa.String(length=256), nullable=True, comment='子类别'),
    sa.Column('lot_id', sa.String(length=128), nullable=True, comment='产品批次 ID'),
    sa.ForeignKeyConstraint(['id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='商品'
    )
    op.create_index('ix_source_product_id', 'product_detail', ['source', 'product_id'], unique=False)
    op.create_table('product_sku_detail',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='内部ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('sku_id', sa.String(length=128), nullable=True, comment='源SKU ID'),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.ForeignKeyConstraint(['id'], ['product_sku.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='商品SKU详情'
    )
    op.create_index('ix_source_sku_id', 'product_sku_detail', ['source', 'sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_sku_id', table_name='product_sku_detail')
    op.drop_table('product_sku_detail')
    op.drop_index('ix_source_product_id', table_name='product_detail')
    op.drop_table('product_detail')
    op.drop_index('ix_source_product_id', table_name='product_translation')
    op.drop_table('product_translation')
    op.drop_index('ix_source_sku_id', table_name='product_sku_translation')
    op.drop_table('product_sku_translation')
    op.drop_index('ix_source_sku_id', table_name='product_sku', mysql_using='hash')
    op.drop_index('ix_source_product_id', table_name='product_sku', mysql_using='hash')
    op.drop_table('product_sku')
    op.drop_index('ix_source_review_id', table_name='product_review_translation')
    op.drop_index('ix_source_product_id', table_name='product_review_translation')
    op.drop_table('product_review_translation')
    op.drop_table('product_review_analysis')
    op.drop_index('ix_source_product_id', table_name='product_review', mysql_using='hash')
    op.drop_table('product_review')
    op.drop_index('ix_source_product_id', table_name='product')
    op.drop_index(op.f('ix_product_released_at'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
