"""set modify product.released_at field type to timestamp

Revision ID: 0a53a742917b
Revises: 9cb88027b4d3
Create Date: 2024-07-16 13:04:36.857648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a53a742917b'
down_revision: Union[str, None] = '9cb88027b4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'released_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_comment='上新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'released_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_comment='上新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
