"""update category field

Revision ID: 14c099e4366b
Revises: e35ae6893607
Create Date: 2024-06-18 00:08:57.969562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c099e4366b'
down_revision: Union[str, None] = 'e35ae6893607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sub_category', sa.String(length=256), nullable=True, comment='子类别'))
    op.add_column('product', sa.Column('inner_category', sa.String(length=256), nullable=True, comment='内部类别'))
    op.add_column('product_sku', sa.Column('gender', sa.String(length=16), nullable=True, comment='性别, 根据类别推断, 主类别'))
    op.add_column('product_sku', sa.Column('sub_category', sa.String(length=256), nullable=True, comment='商品类别'))
    op.add_column('product_sku', sa.Column('inner_category', sa.String(length=256), nullable=True, comment='内部类别'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sku', 'inner_category')
    op.drop_column('product_sku', 'sub_category')
    op.drop_column('product_sku', 'gender')
    op.drop_column('product', 'inner_category')
    op.drop_column('product', 'sub_category')
    # ### end Alembic commands ###
