"""add attributes_raw field for data clear

Revision ID: 242e921e8150
Revises: 14c099e4366b
Create Date: 2024-06-19 17:21:17.580519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242e921e8150'
down_revision: Union[str, None] = '14c099e4366b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('attributes_raw', sa.JSON(), nullable=True, comment='原始属性'))
    op.add_column('product_sku', sa.Column('attributes_raw', sa.JSON(), nullable=True, comment='原始属性'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sku', 'attributes_raw')
    op.drop_column('product', 'attributes_raw')
    # ### end Alembic commands ###
