"""set default value for review analysis metrics

Revision ID: 2e8b8aed7d1f
Revises: 6e41f206af93
Create Date: 2024-06-26 17:32:39.550374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8b8aed7d1f'
down_revision: Union[str, None] = '6e41f206af93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
