"""add index

Revision ID: 34d571eab0e3
Revises: bd9406e59c10
Create Date: 2024-06-12 16:52:13.583321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d571eab0e3'
down_revision: Union[str, None] = 'bd9406e59c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_source_product_id', 'product', ['source', 'product_id'], unique=False, mysql_using='hash')
    op.create_index('ix_source_product_id', 'product_review', ['source', 'product_id'], unique=False, mysql_using='hash')
    op.create_index('ix_source_product_id', 'product_sku', ['source', 'product_id'], unique=False, mysql_using='hash')
    op.create_index('ix_source_sku_id', 'product_sku', ['source', 'sku_id'], unique=False, mysql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_sku_id', table_name='product_sku', mysql_using='hash')
    op.drop_index('ix_source_product_id', table_name='product_sku', mysql_using='hash')
    op.drop_index('ix_source_product_id', table_name='product_review', mysql_using='hash')
    op.drop_index('ix_source_product_id', table_name='product', mysql_using='hash')
    # ### end Alembic commands ###
