"""add review photos_outer field

Revision ID: 42a3b930624f
Revises: 988c20a2a217
Create Date: 2024-06-21 16:39:41.364138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a3b930624f'
down_revision: Union[str, None] = '988c20a2a217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_review', sa.Column('photos_outer', sa.JSON(), nullable=True, comment='评论外部数据源'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_review', 'photos_outer')
    # ### end Alembic commands ###
