"""add extra_metric table and version manage

Revision ID: 4664a5810f38
Revises: 0a53a742917b
Create Date: 2024-07-16 16:27:53.382447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4664a5810f38'
down_revision: Union[str, None] = '0a53a742917b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_analysis_extra_metric',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('review_id', sa.String(length=64), nullable=True, comment='源评论ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_id', sa.String(length=64), nullable=True, comment='商品ID'),
    sa.Column('version_id', sa.String(length=32), nullable=True, comment='版本ID'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='指标名称'),
    sa.Column('value', sa.Numeric(precision=3, scale=1), nullable=True, comment='指标得分'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品评论额外指标, 支持版本管理'
    )
    op.create_index('ix_source_review_id', 'review_analysis_extra_metric', ['source', 'review_id'], unique=False)
    op.create_index('ix_source_review_id_version_id', 'review_analysis_extra_metric', ['source', 'review_id', 'version_id'], unique=False)
    op.add_column('product', sa.Column('current_version', sa.String(length=32), nullable=True, comment='当前版本'))
    op.add_column('product_review', sa.Column('current_version', sa.String(length=32), nullable=True, comment='当前版本'))
    op.alter_column('product_review_analysis', 'version_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=32),
               nullable=True,
               existing_comment='版本ID')
    op.create_index('ix_source_review_id', 'product_review_analysis', ['source', 'review_id'], unique=False)
    op.create_index('ix_source_review_id_version_id', 'product_review_analysis', ['source', 'review_id', 'version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_review_id_version_id', table_name='product_review_analysis')
    op.drop_index('ix_source_review_id', table_name='product_review_analysis')
    op.alter_column('product_review_analysis', 'version_id',
               existing_type=sa.String(length=32),
               type_=mysql.INTEGER(),
               nullable=False,
               existing_comment='版本ID')
    op.drop_column('product_review', 'current_version')
    op.drop_column('product', 'current_version')
    op.drop_index('ix_source_review_id_version_id', table_name='review_analysis_extra_metric')
    op.drop_index('ix_source_review_id', table_name='review_analysis_extra_metric')
    op.drop_table('review_analysis_extra_metric')
    # ### end Alembic commands ###
