"""add color field on product table

Revision ID: 4b57a52dfd24
Revises: fea1dd86bb9c
Create Date: 2024-07-01 18:13:19.374421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b57a52dfd24'
down_revision: Union[str, None] = 'fea1dd86bb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('color', sa.String(length=64), nullable=True, comment='颜色'))
    op.create_index('ix_source_product_id_sku_id', 'product', ['source', 'product_id', 'sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_product_id_sku_id', table_name='product')
    op.drop_column('product', 'color')
    # ### end Alembic commands ###
