"""add review analysis metrics

Revision ID: 6e41f206af93
Revises: cf2a0230a5c4
Create Date: 2024-06-26 17:12:04.469043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e41f206af93'
down_revision: Union[str, None] = 'cf2a0230a5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_review', sa.Column('quality', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品质量指标'))
    op.add_column('product_review', sa.Column('warmth', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品保暖性指标'))
    op.add_column('product_review', sa.Column('comfort', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品舒适度指标'))
    op.add_column('product_review', sa.Column('softness', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品柔软性指标'))
    op.add_column('product_review', sa.Column('preference', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品偏好指标'))
    op.add_column('product_review', sa.Column('repurchase_intent', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品回购意愿指标'))
    op.add_column('product_review', sa.Column('appearance', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品外观指标'))
    op.add_column('product_review', sa.Column('fit', sa.Numeric(precision=3, scale=1), nullable=True, comment='商品合身度指标'))
    op.add_column('product_review', sa.Column('extra_metrics', sa.JSON(), nullable=True, comment='额外评论指标'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_review', 'extra_metrics')
    op.drop_column('product_review', 'fit')
    op.drop_column('product_review', 'appearance')
    op.drop_column('product_review', 'repurchase_intent')
    op.drop_column('product_review', 'preference')
    op.drop_column('product_review', 'softness')
    op.drop_column('product_review', 'comfort')
    op.drop_column('product_review', 'warmth')
    op.drop_column('product_review', 'quality')
    # ### end Alembic commands ###
