"""init 0616

Revision ID: 72798eb45c32
Revises: 
Create Date: 2024-06-16 16:46:42.911625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72798eb45c32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='类别名称'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='数据来源'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父类别ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='类别'
    )
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='内部ID'),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='源产品ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_name', sa.String(length=128), nullable=True, comment='商品名称'),
    sa.Column('sku_id', sa.String(length=128), nullable=True, comment='主款号 ID'),
    sa.Column('brand', sa.String(length=64), nullable=True, comment='品牌'),
    sa.Column('product_url', sa.String(length=1024), nullable=True, comment='商品链接'),
    sa.Column('image_url', sa.String(length=1024), nullable=True, comment='商品主图链接'),
    sa.Column('image_url_outer', sa.String(length=1024), nullable=True, comment='商品图片外链'),
    sa.Column('model_image_url', sa.String(length=1024), nullable=True, comment='模特图片链接'),
    sa.Column('model_image_urls', sa.JSON(), nullable=True, comment='模特图片链接列表'),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True, comment='评分'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='评论数'),
    sa.Column('rating_count', sa.Integer(), nullable=True, comment='评分数'),
    sa.Column('attributes', sa.JSON(), nullable=True, comment='额外商品属性, 特点, 和描述bulletedCopyAttrs'),
    sa.Column('category', sa.String(length=256), nullable=True, comment='商品类别'),
    sa.Column('gender', sa.String(length=16), nullable=True, comment='性别, 根据类别推断'),
    sa.Column('released_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='上新时间'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('style', sa.String(length=64), nullable=True, comment='款式'),
    sa.Column('style_number', sa.String(length=64), nullable=True, comment='款号'),
    sa.Column('type', sa.String(length=64), nullable=True, comment='类型'),
    sa.Column('description', sa.String(length=1024), nullable=True, comment='描述'),
    sa.Column('remark', sa.String(length=1024), nullable=True, comment='备注'),
    sa.Column('store', sa.String(length=64), nullable=True, comment='所属商店'),
    sa.Column('source_id', sa.BigInteger(), nullable=True, comment='源商品ID'),
    sa.Column('category_id', sa.BigInteger(), nullable=True, comment='类别ID'),
    sa.Column('size', sa.String(length=64), nullable=True, comment='尺码'),
    sa.Column('material', sa.String(length=128), nullable=True, comment='材质'),
    sa.Column('fit', sa.String(length=128), nullable=True, comment='适合'),
    sa.Column('length', sa.String(length=128), nullable=True, comment='服装长度'),
    sa.Column('neckline', sa.String(length=128), nullable=True, comment='领口'),
    sa.Column('fabric_name', sa.String(length=128), nullable=True, comment='面料名称'),
    sa.Column('clothing_details', sa.String(length=1024), nullable=True, comment='服装细节'),
    sa.Column('package_quantity', sa.Integer(), nullable=True, comment='包装数量'),
    sa.Column('care_instructions', sa.String(length=1024), nullable=True, comment='护理和清洁'),
    sa.Column('origin', sa.String(length=128), nullable=True, comment='产地'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='原始数据, json字段'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='租户ID'),
    sa.Column('tenant_name', sa.String(length=64), nullable=True, comment='租户名称'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('resource_url', sa.String(length=1024), nullable=True, comment='外部资源链接'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品'
    )
    op.create_index('ix_source_product_id', 'product', ['source', 'product_id'], unique=False, mysql_using='hash')
    op.create_table('product_image',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True, comment='所属商品'),
    sa.Column('sku_id', sa.BigInteger(), nullable=True, comment='SKU ID'),
    sa.Column('image_source_url', sa.String(length=1024), nullable=False, comment='图片链接'),
    sa.Column('type', sa.String(length=64), nullable=False, comment='图片类型'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品图片'
    )
    op.create_table('product_review',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=True, comment='源评论ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_id', sa.String(length=64), nullable=True, comment='商品ID'),
    sa.Column('product_name', sa.String(length=128), nullable=True, comment='商品标题'),
    sa.Column('sku_id', sa.String(length=64), nullable=True, comment='SKU ID'),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True, comment='评分'),
    sa.Column('title', sa.String(length=1024), nullable=True, comment='评论标题'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评论内容'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('helpful_votes', sa.Integer(), nullable=True, comment='按顶票数'),
    sa.Column('not_helpful_votes', sa.Integer(), nullable=True, comment='按踩票数'),
    sa.Column('helpful_score', sa.Numeric(precision=6, scale=1), nullable=True, comment='有用评分'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品评论'
    )
    op.create_index('ix_source_product_id', 'product_review', ['source', 'product_id'], unique=False, mysql_using='hash')
    op.create_table('product_sku',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='内部ID'),
    sa.Column('sku_id', sa.String(length=128), nullable=True, comment='源SKU ID'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.Column('product_name', sa.String(length=128), nullable=True, comment='商品名称'),
    sa.Column('size', sa.String(length=64), nullable=True, comment='尺码'),
    sa.Column('color', sa.String(length=64), nullable=True, comment='颜色'),
    sa.Column('material', sa.String(length=128), nullable=True, comment='材质'),
    sa.Column('source_id', sa.BigInteger(), nullable=True, comment='源商品ID'),
    sa.Column('sku_name', sa.String(length=128), nullable=True, comment='SKU名称'),
    sa.Column('description', sa.String(length=1024), nullable=True, comment='商品描述'),
    sa.Column('attributes', sa.JSON(), nullable=True, comment='额外商品属性, 特点, 和描述bulletedCopyAttrs'),
    sa.Column('product_url', sa.String(length=1024), nullable=True, comment='商品链接'),
    sa.Column('category_id', sa.BigInteger(), nullable=True, comment='类别ID'),
    sa.Column('image_url', sa.String(length=512), nullable=True, comment='商品图片'),
    sa.Column('image_url_outer', sa.String(length=1024), nullable=True, comment='商品图片外链'),
    sa.Column('model_image_url', sa.String(length=1024), nullable=True, comment='模特图片链接'),
    sa.Column('model_image_urls', sa.JSON(), nullable=True, comment='模特图片链接列表'),
    sa.Column('style', sa.String(length=128), nullable=True, comment='服装风格'),
    sa.Column('inventory', sa.Integer(), nullable=True, comment='库存'),
    sa.Column('inventory_status', sa.String(length=32), nullable=True, comment='库存状态'),
    sa.Column('vendor', sa.String(length=64), nullable=True, comment='供应商'),
    sa.Column('fit', sa.String(length=128), nullable=True, comment='适合人群'),
    sa.Column('origin', sa.String(length=128), nullable=True, comment='产地'),
    sa.Column('length', sa.String(length=128), nullable=True, comment='服装长度'),
    sa.Column('neckline', sa.String(length=128), nullable=True, comment='领口'),
    sa.Column('fabric_name', sa.String(length=128), nullable=True, comment='面料名称'),
    sa.Column('clothing_details', sa.String(length=1024), nullable=True, comment='服装细节'),
    sa.Column('package_quantity', sa.Integer(), nullable=True, comment='包装数量'),
    sa.Column('care_instructions', sa.String(length=1024), nullable=True, comment='护理和清洁'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品SKU'
    )
    op.create_index('ix_source_product_id', 'product_sku', ['source', 'product_id'], unique=False, mysql_using='hash')
    op.create_index('ix_source_sku_id', 'product_sku', ['source', 'sku_id'], unique=False, mysql_using='hash')
    op.create_table('task_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='数据来源'),
    sa.Column('task_id', sa.String(length=128), nullable=False, comment='任务ID'),
    sa.Column('status', sa.String(length=64), nullable=False, comment='任务状态'),
    sa.Column('message', sa.String(length=1024), nullable=True, comment='消息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务状态'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_status')
    op.drop_index('ix_source_sku_id', table_name='product_sku', mysql_using='hash')
    op.drop_index('ix_source_product_id', table_name='product_sku', mysql_using='hash')
    op.drop_table('product_sku')
    op.drop_index('ix_source_product_id', table_name='product_review', mysql_using='hash')
    op.drop_table('product_review')
    op.drop_table('product_image')
    op.drop_index('ix_source_product_id', table_name='product', mysql_using='hash')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
