"""sku add attributes field

Revision ID: 75075cd4f9b4
Revises: 790118e56535
Create Date: 2024-06-11 19:42:32.016596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75075cd4f9b4'
down_revision: Union[str, None] = '790118e56535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sku', sa.Column('attributes', sa.JSON(), nullable=True, comment='额外商品属性, 特点, 和描述bulletedCopyAttrs'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sku', 'attributes')
    # ### end Alembic commands ###
