"""init

Revision ID: 790118e56535
Revises: 
Create Date: 2024-06-11 14:02:22.852486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '790118e56535'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=True, comment='商品ID'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='数据来源'),
    sa.Column('task_id', sa.String(length=128), nullable=False, comment='任务ID'),
    sa.Column('status', sa.String(length=64), nullable=False, comment='任务状态'),
    sa.Column('message', sa.String(length=1024), nullable=True, comment='消息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务状态'
    )
    op.alter_column('product_review', 'title',
               existing_type=mysql.VARCHAR(length=1024),
               comment='评论标题',
               existing_nullable=True)
    op.alter_column('product_review', 'comment',
               existing_type=mysql.TEXT(),
               comment='评论内容',
               existing_nullable=True)
    op.alter_column('product_review', 'helpful_score',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               comment='有用评分',
               existing_nullable=True)
    op.alter_column('product_sku', 'sku_name',
               existing_type=mysql.VARCHAR(length=128),
               comment='SKU名称',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_sku', 'sku_name',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='SKU名称',
               existing_nullable=True)
    op.alter_column('product_review', 'helpful_score',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               comment=None,
               existing_comment='有用评分',
               existing_nullable=True)
    op.alter_column('product_review', 'comment',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='评论内容',
               existing_nullable=True)
    op.alter_column('product_review', 'title',
               existing_type=mysql.VARCHAR(length=1024),
               comment=None,
               existing_comment='评论标题',
               existing_nullable=True)
    op.drop_table('task_status')
    # ### end Alembic commands ###
