"""add create_time_inner update_time_inner field

Revision ID: 7a001cf0ec32
Revises: 42a3b930624f
Create Date: 2024-06-24 16:33:39.321200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a001cf0ec32'
down_revision: Union[str, None] = '42a3b930624f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_at_inner', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部创建时间'))
    op.add_column('product', sa.Column('updated_at_inner', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部更新时间'))
    op.add_column('product_review', sa.Column('created_at_inner', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部创建时间'))
    op.add_column('product_review', sa.Column('updated_at_inner', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部更新时间'))
    op.add_column('product_sku', sa.Column('created_at_inner', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部创建时间'))
    op.add_column('product_sku', sa.Column('updated_at_inner', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部更新时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sku', 'updated_at_inner')
    op.drop_column('product_sku', 'created_at_inner')
    op.drop_column('product_review', 'updated_at_inner')
    op.drop_column('product_review', 'created_at_inner')
    op.drop_column('product', 'updated_at_inner')
    op.drop_column('product', 'created_at_inner')
    # ### end Alembic commands ###
