"""add is_review_analyzed field on product table

Revision ID: 838002dbc57c
Revises: 7a001cf0ec32
Create Date: 2024-06-25 16:42:27.591588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838002dbc57c'
down_revision: Union[str, None] = '7a001cf0ec32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_review_analyzed', sa.Boolean(), nullable=True, comment='是否已分析'))
    op.add_column('product', sa.Column('review_analyses', sa.JSON(), nullable=True, comment='评论分析结果汇总'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'review_analyses')
    op.drop_column('product', 'is_review_analyzed')
    # ### end Alembic commands ###
