"""add extra_metric name index

Revision ID: 9640cb3e21d0
Revises: 97332937f225
Create Date: 2024-07-18 15:24:16.441846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9640cb3e21d0'
down_revision: Union[str, None] = '97332937f225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_source_review_id_version_id_name', 'review_analysis_extra_metric', ['source', 'review_id', 'version_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_review_id_version_id_name', table_name='review_analysis_extra_metric')
    # ### end Alembic commands ###
