"""add modify product review_summary data type

Revision ID: 97332937f225
Revises: c89ac7d6a384
Create Date: 2024-07-17 17:42:21.393419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97332937f225'
down_revision: Union[str, None] = 'c89ac7d6a384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'review_summary',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.JSON(),
               existing_comment='评论总结',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'review_summary',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=2048),
               existing_comment='评论总结',
               existing_nullable=True)
    # ### end Alembic commands ###
