"""add review photos field

Revision ID: 988c20a2a217
Revises: 04f76a6770d0
Create Date: 2024-06-21 12:47:40.673197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988c20a2a217'
down_revision: Union[str, None] = '04f76a6770d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_review', sa.Column('photos', sa.JSON(), nullable=True, comment='评论图片'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_review', 'photos')
    # ### end Alembic commands ###
