"""delete source_id in product_sku

Revision ID: 9c06a57edd1c
Revises: fe9ca2204b11
Create Date: 2024-07-15 13:46:50.385900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c06a57edd1c'
down_revision: Union[str, None] = 'fe9ca2204b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sku', 'source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sku', sa.Column('source_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='源商品ID'))
    # ### end Alembic commands ###
