""" add model_images field

Revision ID: bd9406e59c10
Revises: 75075cd4f9b4
Create Date: 2024-06-12 16:38:06.811665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9406e59c10'
down_revision: Union[str, None] = '75075cd4f9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('model_image_url', sa.String(length=1024), nullable=True, comment='模特图片链接'))
    op.add_column('product', sa.Column('model_image_urls', sa.JSON(), nullable=True, comment='模特图片链接列表'))
    op.drop_index('product_review_idx_source_product_id', table_name='product_review')
    op.add_column('product_sku', sa.Column('product_url', sa.String(length=1024), nullable=True, comment='商品链接'))
    op.add_column('product_sku', sa.Column('model_image_url', sa.String(length=1024), nullable=True, comment='模特图片链接'))
    op.add_column('product_sku', sa.Column('model_image_urls', sa.JSON(), nullable=True, comment='模特图片链接列表'))
    op.drop_index('product_sku_idx_source_product_id', table_name='product_sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_sku_idx_source_product_id', 'product_sku', ['source', 'product_id'], unique=False)
    op.drop_column('product_sku', 'model_image_urls')
    op.drop_column('product_sku', 'model_image_url')
    op.drop_column('product_sku', 'product_url')
    op.create_index('product_review_idx_source_product_id', 'product_review', ['source', 'product_id'], unique=False)
    op.drop_column('product', 'model_image_urls')
    op.drop_column('product', 'model_image_url')
    # ### end Alembic commands ###
