"""add unique consgtraint for table

Revision ID: c89ac7d6a384
Revises: 4664a5810f38
Create Date: 2024-07-17 14:51:10.361265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89ac7d6a384'
down_revision: Union[str, None] = '4664a5810f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_id_source', 'product', ['product_id', 'source'])
    op.create_unique_constraint('uq_product_id_source', 'product_detail', ['product_id', 'source'])
    op.create_unique_constraint('uq_review_id_source', 'product_review', ['review_id', 'source'])
    op.create_unique_constraint('uq_product_id_sku_id_source', 'product_sku', ['product_id', 'sku_id', 'source'])
    op.create_unique_constraint('uq_product_id_sku_id_source', 'product_sku_detail', ['product_id', 'sku_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_id_sku_id_source', 'product_sku_detail', type_='unique')
    op.drop_constraint('uq_product_id_sku_id_source', 'product_sku', type_='unique')
    op.drop_constraint('uq_review_id_source', 'product_review', type_='unique')
    op.drop_constraint('uq_product_id_source', 'product_detail', type_='unique')
    op.drop_constraint('uq_product_id_source', 'product', type_='unique')
    # ### end Alembic commands ###
