"""add outer image fields and modify filed name

Revision ID: cf2a0230a5c4
Revises: 838002dbc57c
Create Date: 2024-06-26 13:18:16.137415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf2a0230a5c4'
down_revision: Union[str, None] = '838002dbc57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('outer_image_url', sa.String(length=1024), nullable=True, comment='商品图片外链'))
    op.add_column('product', sa.Column('outer_model_image_url', sa.String(length=1024), nullable=True, comment='外部模特图片链接'))
    op.add_column('product', sa.Column('outer_model_image_urls', sa.JSON(), nullable=True, comment='外部模特图片链接列表'))
    op.add_column('product', sa.Column('inner_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部创建时间'))
    op.add_column('product', sa.Column('inner_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部更新时间'))
    op.drop_column('product', 'updated_at_inner')
    op.drop_column('product', 'created_at_inner')
    op.drop_column('product', 'image_url_outer')
    op.add_column('product_review', sa.Column('outer_photos', sa.JSON(), nullable=True, comment='评论外部数据源'))
    op.add_column('product_review', sa.Column('inner_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部创建时间'))
    op.add_column('product_review', sa.Column('inner_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部更新时间'))
    op.drop_column('product_review', 'updated_at_inner')
    op.drop_column('product_review', 'photos_outer')
    op.drop_column('product_review', 'created_at_inner')
    op.add_column('product_sku', sa.Column('outer_image_url', sa.String(length=1024), nullable=True, comment='商品图片外链'))
    op.add_column('product_sku', sa.Column('outer_model_image_url', sa.String(length=1024), nullable=True, comment='外部模特图片链接'))
    op.add_column('product_sku', sa.Column('outer_model_image_urls', sa.JSON(), nullable=True, comment='外部模特图片链接列表'))
    op.add_column('product_sku', sa.Column('inner_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部创建时间'))
    op.add_column('product_sku', sa.Column('inner_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='内部更新时间'))
    op.drop_column('product_sku', 'updated_at_inner')
    op.drop_column('product_sku', 'created_at_inner')
    op.drop_column('product_sku', 'image_url_outer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sku', sa.Column('image_url_outer', mysql.VARCHAR(length=1024), nullable=True, comment='商品图片外链'))
    op.add_column('product_sku', sa.Column('created_at_inner', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='内部创建时间'))
    op.add_column('product_sku', sa.Column('updated_at_inner', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='内部更新时间'))
    op.drop_column('product_sku', 'inner_updated_at')
    op.drop_column('product_sku', 'inner_created_at')
    op.drop_column('product_sku', 'outer_model_image_urls')
    op.drop_column('product_sku', 'outer_model_image_url')
    op.drop_column('product_sku', 'outer_image_url')
    op.add_column('product_review', sa.Column('created_at_inner', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='内部创建时间'))
    op.add_column('product_review', sa.Column('photos_outer', mysql.JSON(), nullable=True, comment='评论外部数据源'))
    op.add_column('product_review', sa.Column('updated_at_inner', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='内部更新时间'))
    op.drop_column('product_review', 'inner_updated_at')
    op.drop_column('product_review', 'inner_created_at')
    op.drop_column('product_review', 'outer_photos')
    op.add_column('product', sa.Column('image_url_outer', mysql.VARCHAR(length=1024), nullable=True, comment='商品图片外链'))
    op.add_column('product', sa.Column('created_at_inner', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='内部创建时间'))
    op.add_column('product', sa.Column('updated_at_inner', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='内部更新时间'))
    op.drop_column('product', 'inner_updated_at')
    op.drop_column('product', 'inner_created_at')
    op.drop_column('product', 'outer_model_image_urls')
    op.drop_column('product', 'outer_model_image_url')
    op.drop_column('product', 'outer_image_url')
    # ### end Alembic commands ###
