"""update product_review index 

Revision ID: d5ccb594979c
Revises: ebf97b482882
Create Date: 2024-07-31 17:12:56.968953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ccb594979c'
down_revision: Union[str, None] = 'ebf97b482882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_review_id_source', table_name='product_review')
    op.drop_index('ix_source_product_id', table_name='product_review')
    op.create_index('ix_source_product_id', 'product_review', ['source', 'product_id', 'review_id'], unique=False)
    op.create_unique_constraint('uq_review_id_product_id_source', 'product_review', ['review_id', 'product_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_id_product_id_source', 'product_review', type_='unique')
    op.drop_index('ix_source_product_id', table_name='product_review')
    op.create_index('ix_source_product_id', 'product_review', ['source', 'product_id'], unique=False)
    op.create_index('uq_review_id_source', 'product_review', ['review_id', 'source'], unique=True)
    # ### end Alembic commands ###
