"""add index on product.released_at

Revision ID: e35ae6893607
Revises: 72798eb45c32
Create Date: 2024-06-17 17:35:12.476288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35ae6893607'
down_revision: Union[str, None] = '72798eb45c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_released_at', table_name='product')
    op.create_index(op.f('ix_product_released_at'), 'product', ['released_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_released_at'), table_name='product')
    op.create_index('ix_released_at', 'product', ['released_at'], unique=False)
    # ### end Alembic commands ###
