"""add main_category filed on product_detail 

Revision ID: ebf97b482882
Revises: 9640cb3e21d0
Create Date: 2024-07-24 14:27:56.246404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebf97b482882'
down_revision: Union[str, None] = '9640cb3e21d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_detail', sa.Column('main_category', sa.String(length=256), nullable=True, comment='主类别, 用于抓取时类别标识'))
    op.alter_column('product_detail', 'sub_category',
               existing_type=mysql.VARCHAR(length=256),
               comment='子类别, 用于抓取时类别标识',
               existing_comment='子类别',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_detail', 'sub_category',
               existing_type=mysql.VARCHAR(length=256),
               comment='子类别',
               existing_comment='子类别, 用于抓取时类别标识',
               existing_nullable=True)
    op.drop_column('product_detail', 'main_category')
    # ### end Alembic commands ###
