"""delete helpful_socre in product_review

Revision ID: fe9ca2204b11
Revises: 04e93b6e5ac9
Create Date: 2024-07-15 13:04:39.059225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe9ca2204b11'
down_revision: Union[str, None] = '04e93b6e5ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_review', 'helpful_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_review', sa.Column('helpful_score', mysql.DECIMAL(precision=6, scale=1), nullable=True, comment='有用评分'))
    # ### end Alembic commands ###
